### ISSUE TITLE
Linux only builds

### ISSUE THREAD

**Issue by gageorsburn** [mpolednik/linux-vfio-k8s-dpi#55]
While working on PR I noticed this doesn't compile on OSX. My way around this was to add in a multi-stage build Dockerfile to build the project inside a go-lang container.

```
FROM golang:1.10.3 as builder
WORKDIR /go/src/github.com/kubevirt/kubernetes-device-plugins
COPY kubernetes-device-plugins .
RUN cd cmd/network/bridge && go fmt && go vet && go install -v


FROM fedora:27
RUN dnf install -y iproute
COPY --from=builder /go/bin/bridge .
ENTRYPOINT [ "./bridge", "-v", "3", "-logtostderr"]
```

Furthermore is there a reason fedora:27 is being used over say alpine? The image size could go down substantially to ~7-20mb.

**Comment by phoracek** [comment]
Hi @gageorsburn, thanks for opening this. There is a PR for that https://github.com/kubevirt/kubernetes-device-plugins/pull/53. However, we want to make it similar to KubeVirt, where the binary is built in one container, saved on host and then used to build another.

We used Fedora because of we used some command line tools, but it's not true anymore. Using Fedora is not a big deal, since it is used by KubeVirt images, hence available on each Node. But using Alpine sounds reasonable, it may make the development cycle faster.
